before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid


language: java
jdk:
  - openjdk11
script:
  - ./backend/mvnw clean install
git:
  depth: false
branches:
  only:
  - master

