name: Publish Docker image
on:
  release:
    types: [published]
  # push:
  #   branches:
  #     - 'main'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: backend
          dockerfile: backend/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/messenger
          tag_with_ref: true